DROP TABLE IF EXISTS FILMS, FRIENDLIST, GENRE, GENRESLIST, LIKESLIST, MPA, USERS;

CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(50) NOT NULL,
    login    VARCHAR(50) NOT NULL,
    user_name     VARCHAR(50) NOT NULL,
    birthday DATE,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name   VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name   VARCHAR(50)  NOT NULL,
    description VARCHAR(200) NOT NULL,
    releaseDate DATE,
    duration    INT CHECK (duration > 0),
    mpa_id      INT REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS friendList
(
    user_id   INTEGER REFERENCES users (user_id),
    friend_id INTEGER REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS likesList
(
    film_id INTEGER REFERENCES films (film_id),
    user_id INTEGER REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genresList
(
    film_id  INTEGER REFERENCES films (film_id),
    genre_id INTEGER REFERENCES genre (genre_id)
);
